### ISSUE TITLE
"Tap Anywhere" is offensive to people with real computers

### ISSUE THREAD

**Issue by NickJosephson** [jameswklassen/ordering-system-silverware#36]
How can I "Tap Anywhere" on the launch screen when all I have is a mouse.

**Comment by DiljotSG** [comment]
Hi Nick,

Thanks for reaching out! When designing Silverware we intended for terminology like "Tap", "Press" and "Select" to be used interchangeably. We've heard your feedback, and will continue to investigate further. Thanks again for your help in making Silverware better.

**Comment by DiljotSG** [comment]
Hey Nick,

Based on your feedback, we've updated the start screen message. Thanks again!
